package com.neu.wham.prefs.util;

import java.util.HashMap;
import java.util.Map;

public final class EventbritePrefMapping {
	private static final Map<String, String> ePrefs = new HashMap<String, String>();
	
	static {
		// Formats
		ePrefs.put("Conference", "1");
		ePrefs.put("Seminar or Talk", "2");
		ePrefs.put("Tradeshow, Consumer Show, or Expo", "3");
		ePrefs.put("Convention", "4");
		ePrefs.put("Festival or Fair", "5");
		ePrefs.put("Concert or Performance", "6");
		ePrefs.put("Screening", "7");
		ePrefs.put("Dinner or Gala", "8");
		ePrefs.put("Class, Training, or Workshop", "9");
		ePrefs.put("Meeting or Networking Event", "10");
		ePrefs.put("Party or Social Gathering", "11");
		ePrefs.put("Rally", "12");
		ePrefs.put("Tournament", "13");
		ePrefs.put("Game or Competition", "14");
		ePrefs.put("Race or Endurance Event", "15");
		ePrefs.put("Tour", "16");
		ePrefs.put("Attraction", "17");
		ePrefs.put("Camp, Trip, or Retreat", "18");
		ePrefs.put("Appearance or Signing", "19");
		ePrefs.put("Other", "100");
		
		// Categories
		ePrefs.put("Music", "103");
		ePrefs.put("Business & Professional", "101");
		ePrefs.put("Business And Professional", "101");
		ePrefs.put("Food & Drink", "110");
		ePrefs.put("Food And Drink", "110");
		ePrefs.put("Community & Culture", "113");
		ePrefs.put("Community And Culture", "113");
		ePrefs.put("Performing & Visual Arts", "105");
		ePrefs.put("Performing And Visual Arts", "105");
		ePrefs.put("Film, Media & Entertainment", "104");
		ePrefs.put("Film, Media And Entertainment", "104");
		ePrefs.put("Sports & Fitness", "108");
		ePrefs.put("Sports And Fitness", "108");
		ePrefs.put("Health & Wellness", "107");
		ePrefs.put("Health And Wellness", "107");
		ePrefs.put("Science & Technology", "102");
		ePrefs.put("Science And Technology", "102");
		ePrefs.put("Travel & Outdoor", "109");
		ePrefs.put("Travel And Outdoor", "109");
		ePrefs.put("Charity & Causes", "111");
		ePrefs.put("Charity And Causes", "111");
		ePrefs.put("Religion & Spirituality", "114");
		ePrefs.put("Religion And Spirituality", "114");
		ePrefs.put("Family & Education", "115");
		ePrefs.put("Family And Education", "115");
		ePrefs.put("Seasonal & Holiday", "116");
		ePrefs.put("Seasonal And Holiday", "116");
		ePrefs.put("Government & Politics", "112");
		ePrefs.put("Government And Politics", "112");
		ePrefs.put("Fashion & Beauty", "106");
		ePrefs.put("Fashion And Beauty", "106");
		ePrefs.put("Home & Lifestyle", "117");
		ePrefs.put("Home And Lifestyle", "117");
		ePrefs.put("Auto, Boat & Air", "118");
		ePrefs.put("Auto, Boat And Air", "118");
		ePrefs.put("Hobbies & Special Interest", "119");
		ePrefs.put("Hobbies And Special Interest", "119");
		ePrefs.put("Other", "199");

		// Subcategories
		ePrefs.put("Startups & Small Business", "1001");
		ePrefs.put("Startups And Small Business", "1001");
		ePrefs.put("Finance", "1002");
		ePrefs.put("Environment & Sustainability", "1003");
		ePrefs.put("Environment And Sustainability", "1003");
		ePrefs.put("Educators", "1004");
		ePrefs.put("Real Estate", "1005");
		ePrefs.put("Non Profit & NGOs", "1006");
		ePrefs.put("Sales & Marketing", "1007");
		ePrefs.put("Sales And Marketing", "1007");
		ePrefs.put("Media", "1008");
		ePrefs.put("Design", "1009");
		ePrefs.put("Career", "1010");
		ePrefs.put("Other", "1999");
		ePrefs.put("Medicine", "2001");
		ePrefs.put("Science", "2002");
		ePrefs.put("Biotech", "2003");
		ePrefs.put("High Tech", "2004");
		ePrefs.put("Mobile", "2005");
		ePrefs.put("Social Media", "2006");
		ePrefs.put("Robotics", "2007");
		ePrefs.put("Other", "2999");
		ePrefs.put("Alternative", "3001");
		ePrefs.put("Blues & Jazz", "3002");
		ePrefs.put("Classical", "3003");
		ePrefs.put("Country", "3004");
		ePrefs.put("Cultural", "3005");
		ePrefs.put("EDM / Electronic", "3006");
		ePrefs.put("Folk", "3007");
		ePrefs.put("Hip Hop / Rap", "3008");
		ePrefs.put("Indie", "3009");
		ePrefs.put("Latin", "3010");
		ePrefs.put("Metal", "3011");
		ePrefs.put("Opera", "3012");
		ePrefs.put("Pop", "3013");
		ePrefs.put("R&B", "3014");
		ePrefs.put("Reggae", "3015");
		ePrefs.put("Religious/Spiritual", "3016");
		ePrefs.put("Rock", "3017");
		ePrefs.put("Top 40", "3018");
		ePrefs.put("Other", "3999");
		ePrefs.put("TV", "4001");
		ePrefs.put("Film", "4002");
		ePrefs.put("Anime", "4003");
		ePrefs.put("Gaming", "4004");
		ePrefs.put("Comics", "4005");
		ePrefs.put("Adult", "4006");
		ePrefs.put("Comedy", "4007");
		ePrefs.put("Other", "4999");
		ePrefs.put("Theatre", "5001");
		ePrefs.put("Musical", "5002");
		ePrefs.put("Ballet", "5003");
		ePrefs.put("Dance", "5004");
		ePrefs.put("Opera", "5005");
		ePrefs.put("Orchestra", "5006");
		ePrefs.put("Craft", "5007");
		ePrefs.put("Fine Art", "5008");
		ePrefs.put("Literary Arts", "5009");
		ePrefs.put("Comedy", "5010");
		ePrefs.put("Other", "5999");
		ePrefs.put("Fashion", "6001");
		ePrefs.put("Accessories", "6002");
		ePrefs.put("Bridal", "6003");
		ePrefs.put("Beauty", "6004");
		ePrefs.put("Other", "6999");
		ePrefs.put("Personal health", "7001");
		ePrefs.put("Mental health", "7002");
		ePrefs.put("Medical", "7003");
		ePrefs.put("Spa", "7004");
		ePrefs.put("Yoga", "7005");
		ePrefs.put("Other", "7999");
		ePrefs.put("Running", "8001");
		ePrefs.put("Walking", "8002");
		ePrefs.put("Cycling", "8003");
		ePrefs.put("Mountain Biking", "8004");
		ePrefs.put("Obstacles", "8005");
		ePrefs.put("Basketball", "8006");
		ePrefs.put("Football", "8007");
		ePrefs.put("Baseball", "8008");
		ePrefs.put("Soccer", "8009");
		ePrefs.put("Golf", "8010");
		ePrefs.put("Volleyball", "8011");
		ePrefs.put("Tennis", "8012");
		ePrefs.put("Swimming & Water Sports", "8013");
		ePrefs.put("Hockey", "8014");
		ePrefs.put("Motorsports", "8015");
		ePrefs.put("Fighting & Martial Arts", "8016");
		ePrefs.put("Snow Sports", "8017");
		ePrefs.put("Rugby", "8018");
		ePrefs.put("Yoga", "8019");
		ePrefs.put("Exercise", "8020");
		ePrefs.put("Other", "8999");
		ePrefs.put("Hiking", "9001");
		ePrefs.put("Rafting", "9002");
		ePrefs.put("Kayaking", "9003");
		ePrefs.put("Canoeing", "9004");
		ePrefs.put("Climbing", "9005");
		ePrefs.put("Travel", "9006");
		ePrefs.put("Other", "9999");
		ePrefs.put("Beer", "10001");
		ePrefs.put("Wine", "10002");
		ePrefs.put("Food", "10003");
		ePrefs.put("Spirits", "10004");
		ePrefs.put("Other", "10999");
		ePrefs.put("Animal Welfare", "11001");
		ePrefs.put("Environment", "11002");
		ePrefs.put("Healthcare", "11003");
		ePrefs.put("Human Rights", "11004");
		ePrefs.put("International Aid", "11005");
		ePrefs.put("Poverty", "11006");
		ePrefs.put("Disaster Relief", "11007");
		ePrefs.put("Education", "11008");
		ePrefs.put("Other", "11999");
		ePrefs.put("Republican Party", "12001");
		ePrefs.put("Democratic Party", "12002");
		ePrefs.put("Other Party", "12003");
		ePrefs.put("Non-partisan", "12004");
		ePrefs.put("Federal Government", "12005");
		ePrefs.put("State Government", "12006");
		ePrefs.put("County/Municipal Government ", "12007");
		ePrefs.put("Other", "12999");
		ePrefs.put("State", "13001");
		ePrefs.put("County", "13002");
		ePrefs.put("City/Town", "13003");
		ePrefs.put("LGBT", "13004");
		ePrefs.put("Medieval", "13005");
		ePrefs.put("Renaissance", "13006");
		ePrefs.put("Heritage", "13007");
		ePrefs.put("Nationality", "13008");
		ePrefs.put("Language", "13009");
		ePrefs.put("Other", "13999");
		ePrefs.put("Christianity", "14001");
		ePrefs.put("Judaism", "14002");
		ePrefs.put("Islam", "14003");
		ePrefs.put("Mormonism", "14004");
		ePrefs.put("Buddhism", "14005");
		ePrefs.put("Sikhism", "14006");
		ePrefs.put("Eastern Religion", "14007");
		ePrefs.put("Mysticism and Occult", "14008");
		ePrefs.put("New Age", "14009");
		ePrefs.put("Other", "14099");
		ePrefs.put("Education", "15001");
		ePrefs.put("Alumni", "15002");
		ePrefs.put("Parenting", "15003");
		ePrefs.put("Baby", "15004");
		ePrefs.put("Children & Youth ", "15005");
		ePrefs.put("Children And Youth ", "15005");
		ePrefs.put("Parents Association", "15006");
		ePrefs.put("Reunion", "15007");
		ePrefs.put("Other", "15999");
		ePrefs.put("St Patricks Day", "16001");
		ePrefs.put("Easter", "16002");
		ePrefs.put("Independence Day", "16003");
		ePrefs.put("Halloween/Haunt", "16004");
	}
	
	public static final String getEventbritePref(String key) {
		return ePrefs.get(key);
	}
}
